### ISSUE TITLE
Notification area mode

### ISSUE THREAD

**Issue by GoodKey** [lukaszbanasiak/YAPA#13] opened 2014-12-29 12:23 UTC
It would be amazing if YAPA could be integrated in the notification area. Much like Tomighty has integrated their timer in an icon. 

![ss-win 1](https://cloud.githubusercontent.com/assets/6448718/5948269/d708741c-a743-11e4-94b7-b5ec07dcd548.png)

**Comment by AKorets** [comment] 2015-07-23 13:30
Is it solving the issue?

![image](https://cloud.githubusercontent.com/assets/99510/8851425/089052b8-3158-11e5-808e-f06f1986bc01.png)

**Comment by lukaszbanasiak** [comment] 2015-07-24 07:22
@GoodKey What do you think?

FYI @floatas

**Comment by floatas** [comment] 2015-07-24 07:58
I think we should show minutes (in red background when working, green when relaxing or vice versa) and when less then a minute remains display seconds or even full time, need to check is there are width restriction on system tray. Also this would allow to "Minimize to tray", hide timer from desktop.

Additionally Pause/Stop icons can be displayed to indicate applications state when time is not running.

**Comment by GoodKey** [comment] 2015-08-03 07:56
I'd really like it to display the minutes. I think it would make it a great timer, because it already contains the simple pomodoro history tracker :smile:

**Comment by floatas** [comment] 2015-11-07 12:24
This bug was created almost a year ago, seems like yesterday, time flies. Added support for system tray, when minimized minutes will be shown. Would be nice to get some input on design, how to make it better looking. 
![image](https://cloud.githubusercontent.com/assets/7883111/11015149/43801abe-855b-11e5-8def-ccb6844f3ff8.png)

**Comment by Rockietm** [comment] 2015-11-07 14:23
Just wanted to ask about closing to tray ability..

Thank You, will test it! :)

**Comment by Rockietm** [comment] 2015-11-15 09:33
Mmm thank You, but what about <b>still show counter</b> in the corner, but have possibility to <b>minimize not in taskbar but in tray</b>?

You have great feature to show progress on taskbar, I think it is convinient but in my situation I don't need(I can always look on counter in the corner). In opposite - for me YAPA tray tab mixes with firefox or other tabs(like screenshot, tabs are visually similar):

![f_2015-11-15_112026](https://cloud.githubusercontent.com/assets/5569346/11168124/fb517bf8-8b8a-11e5-8938-e749dcaac5c6.png)

1) So if You already make a minimize feature, maybe You make a "Hide from taskbar to tray" option? 

2) I don't know what topic started wanted, but I think "Tray feature" <b>does not assume hide counter</b> from desktop. For me - this is the key feature of program - it always shows transparent coundown on top of other windows and gives ability to control time. It's like "sword of Damocles", always ticks near :) Without it program loses its meaning..

p.s.: also I'd show YAPA back(bring to front from tray) on one mouse click, not on double-click

**Comment by floatas** [comment] 2015-11-15 22:09
1. Well when you minimize application now it is removed from taskbar. Also I think option "Minimze to tray" would be nice in settings.
2. I thinks this would be confusing for most of users, but I can add it as hidden feature.

**Comment by Rockietm** [comment] 2015-11-16 10:42
At first glance "Minimize to tray" works nice!

<blockquote>I thinks this would be confusing for most of users, but I can add it as hidden feature.</blockquote>
Yes, for me it will be very cool if You make "Hide from taskbar" flag in XML, or something like that..(to Show counter on desktop, but do not show in taskbar)

**Comment by floatas** [comment] 2015-11-16 18:21
Added setting in YAPA.exe.config  "ShowInTaskbar", when set to true application will not be visible in taskbar and when minimized will be shown in system tray.

**Comment by Rockietm** [comment] 2015-11-16 18:45
<blockquote>Added setting in YAPA.exe.config "ShowInTaskbar", when set to true application will not be visible in taskbar and when minimized will be shown in system tray.</blockquote>
<b>floatas</b> Awesome! :)
Thank You very much! :)

**Comment by GoodKey** [comment] 2015-11-24 12:18
Cool :smile: when will the next release happen?

**Comment by floatas** [comment] 2015-11-24 13:10
We should ping @lukaszbanasiak for release ;)

**Comment by Rockietm** [comment] 2015-11-24 14:10
Don't rush, for me it crashes sometimes!).. 

Don't understand now if it is a bug, or I compiled something wrong.. I'll make a bugreport soon

**Comment by floatas** [comment] 2015-11-24 14:13
Maybe Debug flag would be useful, when exception occurs to log it somewhere

**Comment by Rockietm** [comment] 2015-11-24 14:43
I have it, but it is not informative. For my first impression it is in this last build, but maybe something remains from previous version. Don't remember if I copy-pasted new *.exe and xml or overwritten all.. I'll test it now

![image](https://cloud.githubusercontent.com/assets/5569346/11369830/8c67c346-92c9-11e5-98e5-cdc143ac2af7.png)

<blockquote>
  Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	yapa.exe
  Problem Signature 02:	1.0.0.1
  Problem Signature 03:	564edd0b
  Problem Signature 04:	System.Drawing
  Problem Signature 05:	4.0.30319.18408
  Problem Signature 06:	52311178
  Problem Signature 07:	7b
  Problem Signature 08:	0
  Problem Signature 09:	AMAG3AACMAWG2XAF344U21ACVE5PSTKL
  OS Version:	6.2.9200.2.0.0.400.8
  Locale ID:	1049
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	1a2a
  Additional Information 4:	1a2aa8e38ac8adbb6fe1e594fa623c2e

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=190175

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
</blockquote>

**Comment by floatas** [comment] 2015-11-24 14:54
Do you perform any specific action ? time ends or starts ? Or just randomly stops working ?

**Comment by Rockietm** [comment] 2015-11-24 16:47
Randomly crashes. Works about 20 with something minutes, and then suddenly gives exception. If I compile it in "Debug" mode and make in VS 2013 Attach -> Process - will it give something? Maybe I'll see call stack or place in code that throws exception

**Comment by floatas** [comment] 2015-12-16 19:36
Did small change, looks like there was small "memory leak" icons has to be manually destroyed.

Also added two configuration parameters if someone wants to change tray text color, BreakTrayIconColor and WorkTrayIconColor. Any of these values can be used https://msdn.microsoft.com/en-us/library/system.drawing.color(v=vs.110).aspx

**Comment by Gennady-G** [comment] 2015-12-18 12:03
Hi <b>floatas</b>!

Thank You!

2) Out of curiosity(feature is not for me) changed colors, but don't see the effect..
Lately can check on clear machine

My settings:
```
            <setting name="CountBackwards" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="MinimizeToTray" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ShowInTaskbar" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="BreakTrayIconColor" serializeAs="String">
                <value>Chartreuse</value>
            </setting>
            <setting name="WorkTrayIconColor" serializeAs="String">
                <value>Blue</value>
            </setting>
        </YAPA.Properties.Settings>
```
1) Looks like "crashes" are gone, very good news! :)

**Comment by floatas** [comment] 2015-12-18 18:12
Updated how colors are stored, now simply html colors (http://www.w3schools.com/tags/ref_colorpicker.asp) If someone wants to test, better use release configuration. For some reason debug might still use old colors.

**Comment by Gennady-G** [comment] 2015-12-18 19:11
Colors are Ok, they work. The problem is with settings loading: when I copy-paste folder(change location) - settings from <b>YAPA.exe.config</b> apply succesfully

For me there is another issue - I use widescreen monitor and I sticked windows task bar to the left side. And minimized Yapa appears here:

![yapa_2015-12-17_203553](https://cloud.githubusercontent.com/assets/5569346/11904856/a0036378-a5cb-11e5-8d0a-789d891b4ac3.png)

![yapa_2015-12-17_212735](https://cloud.githubusercontent.com/assets/5569346/11904857/a01d5760-a5cb-11e5-8df3-a2bb0e3af5ec.png)

But I think it does not affect "normal users" :)

**Comment by floatas** [comment] 2015-12-18 22:03
Can you put it in separate bug ? will be easier to track progress on issues, this one is getting a bit too long

**Comment by Gennady-G** [comment] 2015-12-19 10:36
Of course! Created https://github.com/lukaszbanasiak/YAPA/issues/27. I think it could be marked as non-critical, situation when it reproduces is rare

**Comment by floatas** [comment] 2016-09-09 13:07
Notification area mode implemented, last comment left almost a year ago. If there are any more issues with it, please create new bug.

**Closed by floatas** 2016-09-09 13:07 UTC
Labels: enhancement
